# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppTransClustFile <- function(filename, file_type, params) {
    .Call('_transclustr_cppTransClustFile', PACKAGE = 'transclustr', filename, file_type, params)
}

cppTransClustDist <- function(sim_matrix_1d, num_o, params) {
    .Call('_transclustr_cppTransClustDist', PACKAGE = 'transclustr', sim_matrix_1d, num_o, params)
}

